name: tdt4265-group32
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - ultralytics
    - torch>=1.7
    - torchvision>=0.8
    - torchsummary
    - matplotlib>=3.2.2
    - numpy>=1.18.5
    - opencv-python-headless
    - Pillow
    - PyYAML>=5.3.1
    - scipy>=1.4.1
    - tqdm>=4.41.0
    - tensorboard>=2.4.1
    - seaborn>=0.11.0
    - pandas
    - supervision
    - imageio[ffmpeg]
    - scikit-learn
    - codecarbon
    - moviepy
