source: 'ultralytics/assets'
conf: 0.25
iou: 0.7
imgsz: 640
half: False
device: None
max_det: 300
vid_stride: 1
stream_buffer: False
visualize: False
augment: False
agnostic_nms: False
classes: None
retina_masks: False
embed: None