max_lr: 0.01
weight_decay: 0.0001
momentum: 0.9
max_epochs: 100
batch_size: 128

in_channels: 3
num_classes: 8
use_pretrained_weights: true

test_model: false
checkpoint_path: #checkpoints/FasterRCNN/
early_stopping_patience: 10
num_workers: 16
check_val_every_n_epoch: 1
devices: auto
enable_progress_bar: true

wandb_project: NAPLab-LiDAR
wandb_experiment_name: FasterRCNN

train_split_ratio: 0.8
data_root: ./datasets
checkpoint_folder: ./checkpoints/FasterRCNN/


