model_path: runs/detect/train/weights/best.pt # Path to the trained model
params: # Parameters for YOLO prediction
  source: datasets/NAPLab-LiDAR/images/test
  show: false
video: # Parameters for creating video
  create_video: true
  path: results/YOLOv8/videos
  filename: test
  fps: 5
  extension: gif