model_path: yolov8m.pt # Typically pretrained (ex. yolov8m.pt)
loss_function: # Modifications to loss func.
  use_dfl: true
  use_giou: false
  use_diou: false
  use_ciou: true
params: # Hyperparams for YOLOv8 training
  data: datasets/NAPLab-LiDAR/data.yaml
  name: train
  time: 12
  imgsz: 1024
  hsv_h: 0.0
  hsv_s: 0.0