model_path: yolov8m.pt # Typically pretrained weights (ex. yolov8l.pt)
loss_function: # Loss function to use
  use_dfl: true
  use_giou: false
  use_diou: false
  use_ciou: true
params: # Parameters for YOLO training
  data: datasets/NAPLab-LiDAR/data.yaml
  time: 6
  imgsz: 1024
  hsv_h: 0.0
  hsv_s: 0.0